openapi: 3.0.0
info:
  title: WebNotes API
  description: API for managing notes in the WebNotes app
  version: 1.0.0

servers:
  - url: https://api.webnotes.com/v1
    description: Production server

tags:
  - name: notes
    description: Endpoints related to note management

paths:
  /notespreviews:
    get:
      summary: Get all note previews
      description: Returns a list of note previews with truncated text.
      tags:
        - notes
      responses:
        '200':
          description: A list of note previews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotePreview'

  /notes/{id}:
    get:
      summary: Get a note by ID
      description: Returns a full note by its ID.
      tags:
        - notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Note found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '404':
          description: Note not found
    put:
      summary: Update an existing note
      description: Updates an existing note based on its ID.
      tags:
        - notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '200':
          description: Note updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Invalid request data
        '404':
          description: Note not found
    delete:
      summary: Delete a note by ID
      description: Deletes a note from the system.
      tags:
        - notes
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Note deleted successfully
        '404':
          description: Note not found

  /notes:
    post:
      summary: Create a new note
      description: Creates a new note and returns the created note object.
      tags:
        - notes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Note'
      responses:
        '201':
          description: Note created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: Invalid request data

  /notes/recent:
    get:
      summary: Get 5 most recently opened notes
      description: Returns the last 5 opened notes when the app starts.
      tags:
        - notes
      responses:
        '200':
          description: Recently opened notes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'

components:
  schemas:
    NotePreview:
      type: object
      properties:
        id:
          type: string
        bookmark:
          $ref: '#/components/schemas/Bookmark'
        textPreview:
          type: string
          maxLength: 200

    Note:
      type: object
      properties:
        id:
          type: string
        bookmark:
          $ref: '#/components/schemas/Bookmark'
        text:
          type: string

    Bookmark:
      type: object
      properties:
        title:
          type: string
        color:
          type: string
        updatedAt:
          type: string
          format: date-time

    BookmarkWithNoteId:
      allOf:
        - $ref: '#/components/schemas/Bookmark'
        - type: object
          properties:
            id:
              type: string

    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        verified:
          type: boolean
        createAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
